[general]
import = [
    "~/.config/alacritty/themes/themes/alabaster_dark.toml"
]

[env]
TERM = "xterm-256color"

[window]

padding.x = 2
padding.y = 2

decorations = "Buttonless"

option_as_alt = "Both"

startup_mode = "Maximized"

opacity = 1


[font]
normal.family = "JetBrainsMono Nerd Font"
bold.family = "JetBrainsMono Nerd Font"
italic.family = "JetBrainsMono Nerd Font"

size = 20

[cursor]
style.shape = "Block"
style.blinking = "Off"
vi_mode_style.shape = "Block"

[mouse]
hide_when_typing = true

[selection]

save_to_clipboard = true
